
export const CAP = Object.freeze({
  GENERATE_ENVIRONMENT: "GENERATE_ENVIRONMENT",
  GENERATE_IMAGE: "GENERATE_IMAGE",
  EDIT_IMAGE: "EDIT_IMAGE",
  COMPOSITE_PRODUCT: "COMPOSITE_PRODUCT",
  PRODUCT_LOCK: "PRODUCT_LOCK",
  LAYOUT: "LAYOUT",
  GENERATE_COPY: "GENERATE_COPY",
  UPSCALE: "UPSCALE",
  VISUAL_QC: "VISUAL_QC",
  BRAND_QC: "BRAND_QC",
  EXPORT: "EXPORT"
});

export const CREATIVE_TYPES = Object.freeze({
  PRODUCT_HERO: "PRODUCT_HERO",
  STILL_LIFE: "STILL_LIFE",
  CLEAN_SOCIAL: "CLEAN_SOCIAL",
  TYPOGRAPHY_POST: "TYPOGRAPHY_POST",
  CAROUSEL: "CAROUSEL",
  REPURPOSE: "REPURPOSE"
});

export const NODE_STATUS = Object.freeze({
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  PASSED: "PASSED",
  FAILED: "FAILED",
  BLOCKED: "BLOCKED"
});
